import {
  BestiaryEntry,
  CharacterConfig,
  MetaUpgrade,
  PassiveDefinition,
  StageConfig,
  StageId,
  WeaponDefinition,
  WeatherState,
  WeatherType,
} from '../types/survivors';

export const WEAPON_DEFS: Record<string, WeaponDefinition> = {
  whip: {
    id: 'whip',
    name: 'Relho de Couro Cru',
    description: 'Golpeia horizontalmente em arco rasgando os inimigos com estalo de couro trançado.',
    icon: '🪢',
    isEvolution: false,
    evolutionPair: 'armor',
    maxLevel: 6,
    baseDamage: 26,
    baseCooldown: 1.35,
    baseArea: 95,
    baseSpeed: 1,
    baseDuration: 0.25,
    baseAmount: 1,
    damageType: 'melee',
    upgradeDescriptions: [
      'Dispara 1 estalo horizontal veloz.',
      'Dano base aumentado em +12.',
      '+1 golpe adicional para trás.',
      'Dano aumentado em +12 e Área +20%.',
      '+1 golpe adicional e Dano +15.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! Área +25% e Crítico Dobrado.',
    ],
  },
  bloody_tear: {
    id: 'bloody_tear',
    name: 'Relho Farroupilha Sangrento',
    description: 'Fusão Suprema: Estalos em arco duplo com dano devastador, acertos críticos maciços e roubo de vida constante.',
    icon: '🩸',
    isEvolution: true,
    baseWeapon: 'whip',
    evolutionPair: 'armor',
    maxLevel: 1,
    baseDamage: 70,
    baseCooldown: 1.05,
    baseArea: 150,
    baseSpeed: 1,
    baseDuration: 0.3,
    baseAmount: 3,
    damageType: 'melee',
    upgradeDescriptions: ['Habilidade Suprema: Rasga hordas inteiras em arco duplo, regenerando 8 HP a cada golpe crítico.'],
  },

  flying_swords: {
    id: 'flying_swords',
    name: 'Facões Crioulos',
    description: 'Lâminas afiadas de aço puro que giram em torno do peão, retalhando quem se aproximar.',
    icon: '🗡️',
    isEvolution: false,
    evolutionPair: 'empty_tome',
    maxLevel: 6,
    baseDamage: 20,
    baseCooldown: 3.0,
    baseArea: 80,
    baseSpeed: 3.0,
    baseDuration: 3.2,
    baseAmount: 2,
    damageType: 'projectile',
    upgradeDescriptions: [
      'Dois facões afiados orbitam cortando quem se aproxima.',
      '+1 Facão adicional e Dano +6.',
      'Velocidade de rotação +25% e Duração +0.6s.',
      '+1 Facão adicional e Área +20%.',
      'Dano base +10 e Duração +1.0s.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +2 Facões e Rotação Acelerada.',
    ],
  },
  thousand_swords: {
    id: 'thousand_swords',
    name: 'Adaga Farroupilha de Prata',
    description: 'Fusão Suprema: Barreira impenetrável de lâminas de prata girando em velocidade extrema contínua.',
    icon: '⚔️',
    isEvolution: true,
    baseWeapon: 'flying_swords',
    evolutionPair: 'empty_tome',
    maxLevel: 1,
    baseDamage: 50,
    baseCooldown: 0.1,
    baseArea: 120,
    baseSpeed: 4.5,
    baseDuration: 9999,
    baseAmount: 10,
    damageType: 'projectile',
    upgradeDescriptions: ['Habilidade Suprema: Rotação permanente ultra-veloz de 10 lâminas que trituram os monstros sem cessar.'],
  },

  garlic: {
    id: 'garlic',
    name: 'Roda de Chimarrão',
    description: 'Cuia amarga que gera um calor acolhedor no galpão, repelindo assombrações e feras da noite.',
    icon: '🧉',
    isEvolution: false,
    evolutionPair: 'pummarola',
    maxLevel: 6,
    baseDamage: 10,
    baseCooldown: 0.38,
    baseArea: 85,
    baseSpeed: 1,
    baseDuration: 9999,
    baseAmount: 1,
    damageType: 'aura',
    upgradeDescriptions: [
      'Aura quente de erva-mate que machuca e empurra inimigos próximos.',
      'Área aumentada em +25% e Dano +4.',
      'Dano +5 e recuo de inimigos aumentado.',
      'Área aumentada em +25% e Dano +5.',
      'Dano +6 e pulso mais acelerado.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! Área +35% e repele projéteis fracos.',
    ],
  },
  soul_eater: {
    id: 'soul_eater',
    name: 'Cevador da Querência',
    description: 'Fusão Suprema: Pulso colossal de fumaça de galpão e chimarrão que drena a vitalidade dos monstros.',
    icon: '🌟',
    isEvolution: true,
    baseWeapon: 'garlic',
    evolutionPair: 'pummarola',
    maxLevel: 1,
    baseDamage: 38,
    baseCooldown: 0.22,
    baseArea: 170,
    baseSpeed: 1,
    baseDuration: 9999,
    baseAmount: 1,
    damageType: 'aura',
    upgradeDescriptions: ['Habilidade Suprema: Pulso colossal contínuo, recupera vida ao derrotar monstros e ganha dano cumulativo.'],
  },

  magic_wand: {
    id: 'magic_wand',
    name: 'Boleadeira de Arremesso',
    description: 'Dispara boleadeiras certeiras no inimigo mais próximo com força campeira.',
    icon: '🪨',
    isEvolution: false,
    evolutionPair: 'empty_tome',
    maxLevel: 6,
    baseDamage: 24,
    baseCooldown: 1.15,
    baseArea: 1,
    baseSpeed: 400,
    baseDuration: 2.5,
    baseAmount: 1,
    damageType: 'projectile',
    upgradeDescriptions: [
      'Dispara 1 boleadeira veloz teleguiada no inimigo mais próximo.',
      '+1 Boleadeira disparada e Dano +6.',
      '+1 Boleadeira e Perfuração +1 alvo.',
      'Tempo de recarga reduzido em -0.25s e Dano +8.',
      '+1 Boleadeira e Velocidade de projétil +30%.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +1 Projétil e Rajada Contínua.',
    ],
  },
  holy_wand: {
    id: 'holy_wand',
    name: 'Boleadeira de Ouro do Domador',
    description: 'Fusão Suprema: Metralhadora campeira ininterrupta de boleadeiras de ouro sem tempo de recarga.',
    icon: '💫',
    isEvolution: true,
    baseWeapon: 'magic_wand',
    evolutionPair: 'empty_tome',
    maxLevel: 1,
    baseDamage: 48,
    baseCooldown: 0.11,
    baseArea: 1,
    baseSpeed: 550,
    baseDuration: 2.8,
    baseAmount: 3,
    damageType: 'projectile',
    upgradeDescriptions: ['Habilidade Suprema: Disparo ininterrupto com ricochete e perfuração quádrupla.'],
  },

  lightning_ring: {
    id: 'lightning_ring',
    name: 'Faísca do Minuano',
    description: 'Convoca os relâmpagos cortantes do vento minuano fulminando bandos de monstros no descampado.',
    icon: '⚡',
    isEvolution: false,
    evolutionPair: 'duplicator',
    maxLevel: 6,
    baseDamage: 45,
    baseCooldown: 3.6,
    baseArea: 60,
    baseSpeed: 1,
    baseDuration: 0.2,
    baseAmount: 2,
    damageType: 'strike',
    upgradeDescriptions: [
      'Convoca 2 faíscas cortantes em posições de monstros.',
      '+1 Faísca e Dano +12.',
      'Área de impacto aumentada em +30% e Dano +10.',
      '+1 Faísca e Tempo de recarga reduzido em -0.5s.',
      '+1 Faísca e Área +30%.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! Tempestade em cadeia de +2 Raios.',
    ],
  },
  thunder_loop: {
    id: 'thunder_loop',
    name: 'Tormenta dos Pampas',
    description: 'Fusão Suprema: Raios duplos em cadeia do temporal sulista que pulverizam hordas inteiras.',
    icon: '🌩️',
    isEvolution: true,
    baseWeapon: 'lightning_ring',
    evolutionPair: 'duplicator',
    maxLevel: 1,
    baseDamage: 105,
    baseCooldown: 2.0,
    baseArea: 95,
    baseSpeed: 1,
    baseDuration: 0.35,
    baseAmount: 6,
    damageType: 'strike',
    upgradeDescriptions: ['Habilidade Suprema: Cada relâmpago atinge o chão e ricocheteia arcos de pura eletricidade farroupilha.'],
  },

  holy_water: {
    id: 'holy_water',
    name: 'Trago de Cachaça da Serra',
    description: 'Lança garrafas de canha boa que se espatifam no chão criando labaredas de fogo de chão.',
    icon: '🍾',
    isEvolution: false,
    evolutionPair: 'candelabrador',
    maxLevel: 6,
    baseDamage: 18,
    baseCooldown: 3.3,
    baseArea: 70,
    baseSpeed: 210,
    baseDuration: 3.2,
    baseAmount: 1,
    damageType: 'aoe',
    upgradeDescriptions: [
      'Gera 1 poça de fogo de chão quente e duradoura.',
      '+1 Garrafa adicional e Dano +6.',
      'Duração do fogo +1.0s e Área +25%.',
      '+1 Garrafa e Dano +8.',
      '+1 Garrafa e Duração +1.5s.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +1 Garrafa e labaredas gigantescas.',
    ],
  },
  la_borra: {
    id: 'la_borra',
    name: 'Fogo de Chão Sagrado',
    description: 'Fusão Suprema: Labaredas vivas de fogo de chão que crescem e se movem ao redor do peão.',
    icon: '🔥',
    isEvolution: true,
    baseWeapon: 'holy_water',
    evolutionPair: 'candelabrador',
    maxLevel: 1,
    baseDamage: 46,
    baseCooldown: 1.7,
    baseArea: 135,
    baseSpeed: 65,
    baseDuration: 6.5,
    baseAmount: 4,
    damageType: 'aoe',
    upgradeDescriptions: ['Habilidade Suprema: Vórtices de brasa viva que acompanham seus passos, criando trincheiras impenetráveis.'],
  },

  daggers: {
    id: 'daggers',
    name: 'Ponteiras de Aço Farrapo',
    description: 'Arremessa rapidamente lâminas afiadas na direção em que o peão está virado.',
    icon: '🔪',
    isEvolution: false,
    evolutionPair: 'wings',
    maxLevel: 6,
    baseDamage: 18,
    baseCooldown: 0.85,
    baseArea: 1,
    baseSpeed: 470,
    baseDuration: 2.0,
    baseAmount: 2,
    damageType: 'projectile',
    upgradeDescriptions: [
      'Dispara 2 ponteiras na direção para onde você olha.',
      '+1 Ponteira e Dano +5.',
      '+1 Ponteira e Perfura +1 inimigo.',
      '+1 Ponteira e Velocidade +25%.',
      '+1 Ponteira e Dano +8.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +2 Ponteiras e Perfuração Ilimitada.',
    ],
  },
  thousand_blades: {
    id: 'thousand_blades',
    name: 'Chuva de Lâminas Gaudérias',
    description: 'Fusão Suprema: Fluxo ininterrupto de lâminas afiadas em disparada contínua veloz.',
    icon: '⚔️',
    isEvolution: true,
    baseWeapon: 'daggers',
    evolutionPair: 'wings',
    maxLevel: 1,
    baseDamage: 38,
    baseCooldown: 0.08,
    baseArea: 1,
    baseSpeed: 680,
    baseDuration: 2.2,
    baseAmount: 1,
    damageType: 'projectile',
    upgradeDescriptions: ['Habilidade Suprema: Gatling ininterrupto de ponteiras de aço farrapo cortando os monstros.'],
  },

  king_bible: {
    id: 'king_bible',
    name: 'Versos do Martin Fierro',
    description: 'Trovas e versos gauchescos orbitam ao redor, protegendo o gaudério com sabedoria da pampa.',
    icon: '📜',
    isEvolution: false,
    evolutionPair: 'spinach',
    maxLevel: 6,
    baseDamage: 18,
    baseCooldown: 4.0,
    baseArea: 65,
    baseSpeed: 2.4,
    baseDuration: 3.4,
    baseAmount: 1,
    damageType: 'projectile',
    upgradeDescriptions: [
      '1 estrofe sagrada orbita ao redor causando dano de perto.',
      '+1 Estrofe e Dano +6.',
      'Velocidade de rotação +25% e Duração +0.6s.',
      '+1 Estrofe e Área +20%.',
      'Dano +10 e Duração +1.0s.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +1 Estrofe e barreira contínua.',
    ],
  },
  unholy_vespers: {
    id: 'unholy_vespers',
    name: 'Gaitaço Campeiro Eterno',
    description: 'Fusão Suprema: Fole de gaita aberto em rotação perpétua de notas que estraçalham as trevas.',
    icon: '🪗',
    isEvolution: true,
    baseWeapon: 'king_bible',
    evolutionPair: 'spinach',
    maxLevel: 1,
    baseDamage: 44,
    baseCooldown: 0.1,
    baseArea: 95,
    baseSpeed: 4.8,
    baseDuration: 9999,
    baseAmount: 6,
    damageType: 'projectile',
    upgradeDescriptions: ['Habilidade Suprema: A gaita não para nunca e forma um escudo sonoro intransponível.'],
  },

  cusco: {
    id: 'cusco',
    name: 'Invocação do Cusco Caramelo',
    description: 'Fiel cão vira-lata caramelo dos pampas que corre pelo campo caçando monstros, mordendo e latindo ondas de choque.',
    icon: '🐕',
    isEvolution: false,
    evolutionPair: 'attractorb',
    maxLevel: 6,
    baseDamage: 22,
    baseCooldown: 0.8,
    baseArea: 1,
    baseSpeed: 230,
    baseDuration: 9999,
    baseAmount: 1,
    damageType: 'melee',
    upgradeDescriptions: [
      'Invoca o fiel Cusco Caramelo que patrulha e morde monstros ao redor.',
      'Dano de mordida +10 e Velocidade de corrida do cusco +20%.',
      'Invoca +1 filhote companheiro (Total de 2 cuscos caramelo!).',
      'Latido do cusco causa onda de choque e empurrão em área.',
      'Dano de mordida +15 e Taxa de ataque +25%.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +1 Cusco Caramelo (3 no total!).',
    ],
  },
  cusco_supremo: {
    id: 'cusco_supremo',
    name: 'Matilha Sagrada dos Pampas',
    description: 'Fusão Suprema: O lendário Cusco Dourado comanda a matilha dos pampas com mordidas ferozes e latidos que atordoam chefes.',
    icon: '🐕‍🦺',
    isEvolution: true,
    baseWeapon: 'cusco',
    evolutionPair: 'attractorb',
    maxLevel: 1,
    baseDamage: 65,
    baseCooldown: 0.35,
    baseArea: 1.3,
    baseSpeed: 340,
    baseDuration: 9999,
    baseAmount: 4,
    damageType: 'melee',
    upgradeDescriptions: ['Habilidade Suprema: 4 Cuscos gigantes dourados destroçam os monstros, latem trovões sagrados e cavam pilas do chão.'],
  },

  espeto_corrido: {
    id: 'espeto_corrido',
    name: 'Espeto de Costela Flamejante',
    description: 'Arremessa espetos de churrasco em brasa viva que empalam e perfuram filas inteiras de monstros.',
    icon: '🍢',
    isEvolution: false,
    evolutionPair: 'candelabrador',
    maxLevel: 6,
    baseDamage: 32,
    baseCooldown: 2.1,
    baseArea: 1,
    baseSpeed: 420,
    baseDuration: 2.2,
    baseAmount: 1,
    damageType: 'projectile',
    upgradeDescriptions: [
      'Dispara 1 espeto incandescente que perfura até 3 monstros.',
      '+1 Espeto adicional e Dano +10.',
      'Perfura +2 monstros adicionais e incendeia os alvos.',
      '+1 Espeto e Velocidade de disparo +25%.',
      'Dano base +15 e Área das brasas aumentada.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! +1 Espeto e perfuração massiva.',
    ],
  },
  espeto_supremo: {
    id: 'espeto_supremo',
    name: 'Gira-Espeto Farroupilha Voraz',
    description: 'Fusão Suprema: Espetos incandescentes em rotação perpétua com estalos de brasa que pulverizam qualquer horda.',
    icon: '🔥',
    isEvolution: true,
    baseWeapon: 'espeto_corrido',
    evolutionPair: 'candelabrador',
    maxLevel: 1,
    baseDamage: 75,
    baseCooldown: 0.9,
    baseArea: 1.4,
    baseSpeed: 520,
    baseDuration: 3.0,
    baseAmount: 5,
    damageType: 'projectile',
    upgradeDescriptions: ['Habilidade Suprema: Dispara rajadas quíntuplas de espetos que explodem em fogo de chão ao atingir o limite.'],
  },

  garrucha: {
    id: 'garrucha',
    name: 'Garrucha de Pederneira',
    description: 'Arma de fogo clássica dos tempos farroupilhas que cospe chumbo e pólvora em cone de alta precisão.',
    icon: '🔫',
    isEvolution: false,
    evolutionPair: 'clover',
    maxLevel: 6,
    baseDamage: 40,
    baseCooldown: 1.8,
    baseArea: 1,
    baseSpeed: 500,
    baseDuration: 1.2,
    baseAmount: 2,
    damageType: 'projectile',
    upgradeDescriptions: [
      'Dispara 2 projéteis de chumbo em cone frontal.',
      '+1 Bala de chumbo e Dano +12.',
      'Chance de crítico dobrada e repulsão ampliada.',
      '+1 Bala e Tempo de recarga reduzido em -0.3s.',
      'Dano base +18 e Perfura +1 inimigo.',
      'NÍVEL MÁXIMO (6): Pronto para FUSÃO SUPREMA! Cone de chumbo duplo.',
    ],
  },
  trabuco_farrapo: {
    id: 'trabuco_farrapo',
    name: 'Trabuco Farroupilha do Bento',
    description: 'Fusão Suprema: Canhão de mão lendário que detona saraivadas contínuas de pólvora, estilhaçando os monstros.',
    icon: '💥',
    isEvolution: true,
    baseWeapon: 'garrucha',
    evolutionPair: 'clover',
    maxLevel: 1,
    baseDamage: 90,
    baseCooldown: 0.5,
    baseArea: 1.2,
    baseSpeed: 600,
    baseDuration: 1.5,
    baseAmount: 6,
    damageType: 'projectile',
    upgradeDescriptions: ['Habilidade Suprema: Saraivadas ininterruptas de balotes explosivos com acertos críticos garantidos.'],
  },
};

export const PASSIVE_DEFS: Record<string, PassiveDefinition> = {
  spinach: {
    id: 'spinach',
    name: 'Costela no Espeto',
    description: 'Sustância gaúcha de galpão: aumenta o dano de todas as armas em +10% por nível.',
    icon: '🍖',
    maxLevel: 5,
    statEffects: [{ stat: 'might', valuePerLevel: 0.1, isMultiplier: true }],
    upgradeDescriptions: [
      'Dano de todas as armas +10%.',
      'Dano de todas as armas +10% (Total +20%).',
      'Dano de todas as armas +10% (Total +30%).',
      'Dano de todas as armas +10% (Total +40%).',
      'Dano de todas as armas +10% (Total +50% MÁX!).',
    ],
  },
  empty_tome: {
    id: 'empty_tome',
    name: 'Gaita Ponto Afinada',
    description: 'Abre e fecha a gaita com destreza: reduz o tempo de recarga de todas as armas em -8% por nível.',
    icon: '🪗',
    maxLevel: 5,
    statEffects: [{ stat: 'cooldownReduction', valuePerLevel: 0.08, isMultiplier: false }],
    upgradeDescriptions: [
      'Recarga de armas -8%.',
      'Recarga de armas -8% (Total -16%).',
      'Recarga de armas -8% (Total -24%).',
      'Recarga de armas -8% (Total -32%).',
      'Recarga de armas -8% (Total -40% MÁX!).',
    ],
  },
  duplicator: {
    id: 'duplicator',
    name: 'Laço de Doze Braças',
    description: 'Trançado firme de couro: armas desferem +1 golpe ou projétil adicional por nível.',
    icon: '🪢',
    maxLevel: 2,
    statEffects: [{ stat: 'amount', valuePerLevel: 1, isMultiplier: false }],
    upgradeDescriptions: [
      'Todas as armas disparam +1 projétil extra.',
      'Todas as armas disparam +1 projétil extra (Total +2 MÁX!).',
    ],
  },
  candelabrador: {
    id: 'candelabrador',
    name: 'Fogueira de São João',
    description: 'Clareia a noite e aquece as brasas: aumenta a área de efeito dos ataques em +10% por nível.',
    icon: '🔥',
    maxLevel: 5,
    statEffects: [{ stat: 'area', valuePerLevel: 0.1, isMultiplier: true }],
    upgradeDescriptions: [
      'Área de ataque aumentada em +10%.',
      'Área de ataque aumentada em +10% (Total +20%).',
      'Área de ataque aumentada em +10% (Total +30%).',
      'Área de ataque aumentada em +10% (Total +40%).',
      'Área de ataque aumentada em +10% (Total +50% MÁX!).',
    ],
  },
  wings: {
    id: 'wings',
    name: 'Bota de Garrão de Potro',
    description: 'Couro macio e leve para galopar a pé: aumenta a velocidade de movimento em +10% por nível.',
    icon: '👢',
    maxLevel: 5,
    statEffects: [{ stat: 'moveSpeed', valuePerLevel: 20, isMultiplier: false }],
    upgradeDescriptions: [
      'Velocidade de movimento +10%.',
      'Velocidade de movimento +10% (Total +20%).',
      'Velocidade de movimento +10% (Total +30%).',
      'Velocidade de movimento +10% (Total +40%).',
      'Velocidade de movimento +10% (Total +50% MÁX!).',
    ],
  },
  attractorb: {
    id: 'attractorb',
    name: 'Guaiaca Crioula de Couro',
    description: 'Bolsa tradicional de couro cru que puxa pilas e gemas com atração campeira (+35px de raio por nível).',
    icon: '🪙',
    maxLevel: 5,
    statEffects: [{ stat: 'magnet', valuePerLevel: 35, isMultiplier: false }],
    upgradeDescriptions: [
      'Raio de coleta de gemas e pilas +35px.',
      'Raio de coleta de gemas e pilas +35px (Total +70px).',
      'Raio de coleta de gemas e pilas +35px (Total +105px).',
      'Raio de coleta de gemas e pilas +35px (Total +140px).',
      'Raio de coleta de gemas e pilas +35px (Total +175px MÁX!).',
    ],
  },
  crown: {
    id: 'crown',
    name: 'Sabedoria do Velho Tropeiro',
    description: 'Causos contados ao pé do fogo: aumenta o ganho de experiência (Tradição) em +10% por nível.',
    icon: '🤠',
    maxLevel: 5,
    statEffects: [{ stat: 'growth', valuePerLevel: 0.1, isMultiplier: true }],
    upgradeDescriptions: [
      'Ganho de experiência +10%.',
      'Ganho de experiência +10% (Total +20%).',
      'Ganho de experiência +10% (Total +30%).',
      'Ganho de experiência +10% (Total +40%).',
      'Ganho de experiência +10% (Total +50% MÁX!).',
    ],
  },
  armor: {
    id: 'armor',
    name: 'Poncho Farroupilha Grosso',
    description: 'Lã pura que apara os cortes e o vento: reduz o dano sofrido em -1 fixo e aumenta o HP Máximo em +15.',
    icon: '🧣',
    maxLevel: 5,
    statEffects: [
      { stat: 'armor', valuePerLevel: 1, isMultiplier: false },
      { stat: 'maxHp', valuePerLevel: 15, isMultiplier: false },
    ],
    upgradeDescriptions: [
      'Dano sofrido -1 e HP Máximo +15.',
      'Dano sofrido -1 e HP Máximo +15 (Total -2 / +30HP).',
      'Dano sofrido -1 e HP Máximo +15 (Total -3 / +45HP).',
      'Dano sofrido -1 e HP Máximo +15 (Total -4 / +60HP).',
      'Dano sofrido -1 e HP Máximo +15 (Total -5 / +75HP MÁX!).',
    ],
  },
  pummarola: {
    id: 'pummarola',
    name: 'Erva-Mate de Primeira',
    description: 'Chimarrão cevado no capricho: regenera 0.5 de vida por segundo por nível.',
    icon: '🧉',
    maxLevel: 5,
    statEffects: [{ stat: 'hpRegen', valuePerLevel: 0.5, isMultiplier: false }],
    upgradeDescriptions: [
      'Regenera +0.5 HP por segundo.',
      'Regenera +0.5 HP por segundo (Total 1.0 HP/s).',
      'Regenera +0.5 HP por segundo (Total 1.5 HP/s).',
      'Regenera +0.5 HP por segundo (Total 2.0 HP/s).',
      'Regenera +0.5 HP por segundo (Total 2.5 HP/s MÁX!).',
    ],
  },
  clover: {
    id: 'clover',
    name: 'Ferradura de Ouro Missioneira',
    description: 'Sorte gaúcha das Missões: aumenta a sorte em +10% (mais críticos e itens raros).',
    icon: '🧲',
    maxLevel: 5,
    statEffects: [{ stat: 'luck', valuePerLevel: 0.1, isMultiplier: true }],
    upgradeDescriptions: [
      'Sorte +10%.',
      'Sorte +10% (Total +20%).',
      'Sorte +10% (Total +30%).',
      'Sorte +10% (Total +40%).',
      'Sorte +10% (Total +50% MÁX!).',
    ],
  },
};

export const CHARACTERS: CharacterConfig[] = [
  {
    id: 'antonio',
    name: 'Gildo Belmont',
    title: 'O Peão Bagual',
    description: 'Especialista em peleia de galpão e relho de couro cru. Ganha +10% de Dano a cada 20 níveis.',
    avatarColor: '#dc2626',
    accentColor: '#f87171',
    startingWeapon: 'whip',
    bonusStats: {
      maxHp: 120,
      hp: 120,
      might: 1.1,
      armor: 1,
    },
    unlocked: true,
    cost: 0,
  },
  {
    id: 'kaisete',
    name: 'Anastácio das Sete Facas',
    title: 'O Gaudério Veterano',
    description: 'Mestre da esgrima crioula que comanda facões voadores de aço. Inicia com +1 Projétil em todas as armas.',
    avatarColor: '#d97706',
    accentColor: '#fbbf24',
    startingWeapon: 'flying_swords',
    bonusStats: {
      maxHp: 100,
      hp: 100,
      amount: 1,
      cooldownReduction: 0.05,
    },
    unlocked: true,
    cost: 0,
  },
  {
    id: 'yueying',
    name: 'Prenda Donatila',
    title: 'A Curandeira Missioneira',
    description: 'Mestra do chimarrão medicinal e da paz espiritual no pago. Inicia com a Roda de Chimarrão e +25% de Área.',
    avatarColor: '#10b981',
    accentColor: '#34d399',
    startingWeapon: 'garlic',
    bonusStats: {
      maxHp: 90,
      hp: 90,
      area: 1.25,
      hpRegen: 0.5,
    },
    unlocked: false,
    cost: 300,
  },
  {
    id: 'gennaro',
    name: 'Bento Belpaese',
    title: 'O Tropeiro Ligeiro',
    description: 'Veloz no trote e certeiro no arremesso de ponteiras de aço. Inicia com +20% de Velocidade de Movimento.',
    avatarColor: '#8b5cf6',
    accentColor: '#a78bfa',
    startingWeapon: 'daggers',
    bonusStats: {
      maxHp: 95,
      hp: 95,
      moveSpeed: 230,
      projectileSpeed: 1.2,
    },
    unlocked: false,
    cost: 600,
  },
  {
    id: 'zephyr',
    name: 'Teixeirinha dos Raios',
    title: 'O Gaiteiro da Tormenta',
    description: 'Toca acordes que invocam faíscas do Minuano cortante. Inicia com a Faísca do Minuano e -10% de Recarga.',
    avatarColor: '#0ea5e9',
    accentColor: '#38bdf8',
    startingWeapon: 'lightning_ring',
    bonusStats: {
      maxHp: 100,
      hp: 100,
      cooldownReduction: 0.1,
      luck: 1.2,
    },
    unlocked: false,
    cost: 1000,
  },
  {
    id: 'neco_caramelo',
    name: 'Tio Neco & Cusco',
    title: 'O Amigo do Vira-Lata',
    description: 'Companheiro inseparável do fiel cachorro vira-lata caramelo dos pampas. Inicia com a Invocação do Cusco e +25px de Atração de Pilas.',
    avatarColor: '#f59e0b',
    accentColor: '#fbbf24',
    startingWeapon: 'cusco',
    bonusStats: {
      maxHp: 110,
      hp: 110,
      moveSpeed: 200,
      magnet: 95,
      luck: 1.15,
    },
    unlocked: true,
    cost: 0,
  },
  {
    id: 'anita_garibaldi',
    name: 'Anita Guerreira',
    title: 'A Heroína Farroupilha',
    description: 'Bravura lendária das peleias do sul. Dispara saraivadas de pederneira e possui poder de ataque ampliado.',
    avatarColor: '#e11d48',
    accentColor: '#f43f5e',
    startingWeapon: 'garrucha',
    bonusStats: {
      maxHp: 105,
      hp: 105,
      might: 1.15,
      moveSpeed: 210,
      projectileSpeed: 1.1,
    },
    unlocked: false,
    cost: 800,
  },
];

export const META_UPGRADES_CONFIG: MetaUpgrade[] = [
  {
    id: 'might',
    name: 'Braço Forte de Laçador',
    description: 'Aumenta permanentemente o dano de todas as armas em +5% por nível.',
    icon: '💪',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 200,
    bonusPerRank: 0.05,
  },
  {
    id: 'armor',
    name: 'Peito de Aço Gaúcho',
    description: 'Reduz o dano recebido em +1 permanentemente por nível.',
    icon: '🛡️',
    currentRank: 0,
    maxRank: 3,
    costPerRank: 300,
    bonusPerRank: 1,
  },
  {
    id: 'maxHp',
    name: 'Fôlego Crioulo',
    description: 'Aumenta a vida máxima do peão em +10% por nível.',
    icon: '❤️',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 150,
    bonusPerRank: 10,
  },
  {
    id: 'hpRegen',
    name: 'Trago Curativo',
    description: 'Regenera +0.2 HP/s permanentemente por nível.',
    icon: '🧉',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 250,
    bonusPerRank: 0.2,
  },
  {
    id: 'cooldownReduction',
    name: 'Destreza Campeira',
    description: 'Reduz o tempo de recarga de armas em -2.5% por nível.',
    icon: '⏱️',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 350,
    bonusPerRank: 0.025,
  },
  {
    id: 'moveSpeed',
    name: 'Galope Ligeiro',
    description: 'Aumenta a velocidade de movimento a pé em +10px/s por nível.',
    icon: '👢',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 200,
    bonusPerRank: 10,
  },
  {
    id: 'magnet',
    name: 'Guaiaca Atraente',
    description: 'Aumenta o raio de coleta de pilas e gemas em +25px por nível.',
    icon: '🪙',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 150,
    bonusPerRank: 25,
  },
  {
    id: 'growth',
    name: 'Tradição do Galpão',
    description: 'Aumenta a experiência ganha em +3% por nível.',
    icon: '📜',
    currentRank: 0,
    maxRank: 5,
    costPerRank: 250,
    bonusPerRank: 0.03,
  },
  {
    id: 'revives',
    name: 'Reza Forte Missioneira',
    description: 'Revive com 50% de vida ao cair na peleia (+1 vida extra).',
    icon: '🕊️',
    currentRank: 0,
    maxRank: 1,
    costPerRank: 1500,
    bonusPerRank: 1,
  },
];

export const STAGES_CONFIG: Record<StageId, StageConfig> = {
  mad_forest: {
    id: 'mad_forest',
    name: 'Coxilhas do Pampa Verde',
    subtitle: 'Onde o vento minuano uiva na noite sem fim',
    description: 'Campos abertos e coxilhas verdejantes iluminadas pelas estrelas da querência. Ponto de partida ideal para o peão afiar o relho contra os guaipecas e assombrações.',
    icon: '🌾',
    difficultyMultiplier: 1.0,
    bgPalette: {
      base: '#0b1310',
      tileA: '#13211b',
      tileB: '#1a2e26',
      border: '#070c0a',
      accent: '#10b981',
      lightTint: 'rgba(16, 185, 129, 0.12)',
    },
    allowedWeather: ['clear', 'rain', 'blood_moon'],
    weatherPool: ['clear', 'rain', 'blood_moon'],
    defaultWeather: 'clear',
    props: ['torch', 'urn'],
    allowedMonsters: ['bat', 'skeleton', 'wolf', 'wraith'],
    unlocked: true,
    cost: 0,
  },
  inlaid_library: {
    id: 'inlaid_library',
    name: 'Galpão Crioulo Centenário',
    subtitle: 'Chão batido iluminado por tocheiros e fumo de corda',
    description: 'Assoalho de madeira nobre e esteios de canela-preta. Assombrações do passado campeiro rondam as mesas de truco e o fogo de chão.',
    icon: '🏚️',
    difficultyMultiplier: 1.25,
    bgPalette: {
      base: '#1a1410',
      tileA: '#2c221b',
      tileB: '#3a2d24',
      border: '#110c08',
      accent: '#f59e0b',
      lightTint: 'rgba(245, 158, 11, 0.15)',
    },
    allowedWeather: ['clear', 'rain', 'ember_storm'],
    weatherPool: ['clear', 'rain', 'ember_storm'],
    defaultWeather: 'rain',
    props: ['torch', 'urn', 'crystal'],
    allowedMonsters: ['ghoul', 'skeleton', 'wraith', 'golem'],
    unlocked: false,
    cost: 250,
  },
  blood_crypt: {
    id: 'blood_crypt',
    name: 'Ruínas de São Miguel das Missões',
    subtitle: 'Solo sagrado e misterioso das antigas missões jesuíticas',
    description: 'Paredões de pedra de arenito vermelho e cruzes jesuíticas. A terra geme sob a fúria das antigas peleias farroupilhas.',
    icon: '⛪',
    difficultyMultiplier: 1.5,
    bgPalette: {
      base: '#17090b',
      tileA: '#281115',
      tileB: '#35161c',
      border: '#0d0405',
      accent: '#ef4444',
      lightTint: 'rgba(239, 68, 68, 0.18)',
    },
    allowedWeather: ['blood_moon', 'ember_storm', 'clear'],
    weatherPool: ['blood_moon', 'ember_storm', 'clear'],
    defaultWeather: 'blood_moon',
    props: ['torch', 'coffin'],
    allowedMonsters: ['bat', 'wraith', 'skeleton', 'golem'],
    unlocked: false,
    cost: 600,
  },
  frost_peaks: {
    id: 'frost_peaks',
    name: 'Serra Gaúcha sob Geada Negra',
    subtitle: 'Campos congelados de geada com frio rengueador',
    description: 'Pinhais de araucária cobertos de geada e desfiladeiros de pedra. O vento minuano sopra cortando a carne do vivente.',
    icon: '❄️',
    difficultyMultiplier: 1.4,
    bgPalette: {
      base: '#0b1622',
      tileA: '#132435',
      tileB: '#1a3148',
      border: '#070e17',
      accent: '#38bdf8',
      lightTint: 'rgba(56, 189, 248, 0.15)',
    },
    allowedWeather: ['blizzard', 'clear', 'rain'],
    weatherPool: ['blizzard', 'clear', 'rain'],
    defaultWeather: 'blizzard',
    props: ['crystal', 'urn'],
    allowedMonsters: ['wolf', 'golem', 'wraith', 'bat'],
    unlocked: false,
    cost: 1000,
  },
  churrascaria_shopping: {
    id: 'churrascaria_shopping',
    name: 'Shopping dos Gaúchos de Apartamento',
    subtitle: 'Ar-condicionado no máximo, vitrines de luxo e café de R$ 25',
    description: 'Um labirinto climatizado de porcelanato e escadas rolantes invadido por hordas de gaúchos de apartamento de bermuda e copo térmico.',
    icon: '🏙️',
    difficultyMultiplier: 1.2,
    bgPalette: {
      base: '#0f172a',
      tileA: '#1e293b',
      tileB: '#334155',
      border: '#020617',
      accent: '#38bdf8',
      lightTint: 'rgba(56, 189, 248, 0.15)',
    },
    allowedWeather: ['clear', 'rain'],
    weatherPool: ['clear', 'rain'],
    defaultWeather: 'clear',
    props: ['urn', 'torch'],
    allowedMonsters: ['gaucho_apartamento', 'bat', 'skeleton'],
    unlocked: false,
    cost: 350,
  },
  lagoa_patos: {
    id: 'lagoa_patos',
    name: 'Lagoa dos Patos & Costa Doce',
    subtitle: 'Brumas eternas sobre os juncais e redemoinhos de areia',
    description: 'A maior laguna do mundo esconde barcos fantasmas e lendas ancestrais. O Saci-Pererê rodopia em redemoinhos e o Boitatá ronda as águas.',
    icon: '🌊',
    difficultyMultiplier: 1.35,
    bgPalette: {
      base: '#061a1e',
      tileA: '#0d2830',
      tileB: '#133945',
      border: '#020d10',
      accent: '#06b6d4',
      lightTint: 'rgba(6, 182, 212, 0.15)',
    },
    allowedWeather: ['rain', 'clear', 'blood_moon'],
    weatherPool: ['rain', 'clear', 'blood_moon'],
    defaultWeather: 'rain',
    props: ['torch', 'urn'],
    allowedMonsters: ['saci', 'ghoul', 'wraith', 'wolf'],
    unlocked: false,
    cost: 700,
  },
  aparados_serra: {
    id: 'aparados_serra',
    name: 'Cânions dos Aparados da Serra',
    subtitle: 'Abismos vertiginosos e florestas sagradas de Araucária',
    description: 'Desfiladeiros ciclópicos e pinheirais imponentes. Lar do lendário Curupira dos pés virados e da flamejante Mula Sem Cabeça.',
    icon: '🌲',
    difficultyMultiplier: 1.6,
    bgPalette: {
      base: '#0f1f14',
      tileA: '#163120',
      tileB: '#1f452d',
      border: '#08120c',
      accent: '#22c55e',
      lightTint: 'rgba(34, 197, 94, 0.15)',
    },
    allowedWeather: ['blizzard', 'rain', 'ember_storm'],
    weatherPool: ['blizzard', 'rain', 'ember_storm'],
    defaultWeather: 'blizzard',
    props: ['crystal', 'urn', 'coffin'],
    allowedMonsters: ['curupira', 'mula_sem_cabeca', 'golem', 'wraith'],
    unlocked: false,
    cost: 1200,
  },
};

export const WEATHER_DEFS: Record<WeatherType, {
  name: string;
  description: string;
  icon: string;
  bonusText: string;
}> = {
  clear: {
    name: 'Noite Estrelada no Pampa',
    description: 'Céu noturno limpo com o Cruzeiro do Sul brilhando. O ar puro fortalece o peão.',
    icon: '✨',
    bonusText: '+15% Regeneração de Vida & Visão Clara',
  },
  rain: {
    name: 'Temporal com Vento Minuano',
    description: 'Temporal de relâmpagos e ventania sulina assobiando nos campos.',
    icon: '🌧️',
    bonusText: '+20% Velocidade de Projéteis & Trovões Sagrados',
  },
  blizzard: {
    name: 'Geada Negra Rengueadora',
    description: 'Frio congelante que bate os queixos e estala nas taipas de pedra.',
    icon: '❄️',
    bonusText: 'Inimigos Desacelerados em -20% & Congelamentos +Longos',
  },
  blood_moon: {
    name: 'Viração Vermelha (Lua Farrapa)',
    description: 'Céu avermelhado que desperta a bravura gaucha e multiplica as pilas!',
    icon: '🩸',
    bonusText: '+35% de Pilas & Experiência Coletados!',
  },
  ember_storm: {
    name: 'Faíscas do Fogo de Chão',
    description: 'Labaredas e fagulhas de fogueira campeira voam pelo campo espalhando calor.',
    icon: '🔥',
    bonusText: 'Ataques aplicam Queimadura em Área (Fogo Crioulo)',
  },
};

export const BESTIARY_DATA: BestiaryEntry[] = [
  {
    id: 'bat',
    name: 'Morcego das Taipas',
    tier: 'mob',
    spriteShape: 'bat',
    description: 'Praga alada das frestas do galpão que ataca em bandos desgovernados.',
    lore: 'Nascidos sob as taipas de pedra da campanha gaúcha, estes morcegos buscam o calor do sangue dos peões.',
    color: '#3b0764',
    secondaryColor: '#581c87',
    baseHp: 14,
    baseDamage: 6,
    baseSpeed: 110,
    xpValue: 1,
    weakness: 'Relho de Couro Cru e Roda de Chimarrão',
    milestones: [
      { kills: 25, rank: 1, title: 'Espanta-Morcegos', bonusDesc: '+5% Pilas de Morcegos' },
      { kills: 100, rank: 2, title: 'Espantador Campeiro', bonusDesc: '+10% Dano contra Morcegos' },
      { kills: 300, rank: 3, title: 'Predador Noturno', bonusDesc: '+20% XP de Morcegos' },
      { kills: 750, rank: 4, title: 'Dono das Taipas', bonusDesc: '+2% Velocidade Global Permanente', bonusStat: 'moveSpeed', bonusValue: 5 },
      { kills: 1500, rank: 5, title: 'Mestre da Noite', bonusDesc: '+3% Sorte Global Permanente', bonusStat: 'luck', bonusValue: 0.03 },
    ],
  },
  {
    id: 'skeleton',
    name: 'Esqueleto Maragato',
    tier: 'mob',
    spriteShape: 'skeleton',
    description: 'Ossadas de antigos combatentes farrapos empunhando facas e lanças de taquara.',
    lore: 'Guerreiros que caíram nas coxilhas e foram despertados por uma mandinga sombria.',
    color: '#e2e8f0',
    secondaryColor: '#94a3b8',
    baseHp: 28,
    baseDamage: 10,
    baseSpeed: 70,
    xpValue: 2,
    weakness: 'Facões Crioulos e Golpes Cortantes Rápidos',
    milestones: [
      { kills: 25, rank: 1, title: 'Quebra-Ossadas', bonusDesc: '+5% Pilas de Esqueletos' },
      { kills: 100, rank: 2, title: 'Triturador de Lanças', bonusDesc: '+10% Dano contra Esqueletos' },
      { kills: 300, rank: 3, title: 'Paz aos Maragatos', bonusDesc: '+20% XP de Esqueletos' },
      { kills: 750, rank: 4, title: 'Veterano das Batalhas', bonusDesc: '+1 Armadura Permanente', bonusStat: 'armor', bonusValue: 1 },
      { kills: 1500, rank: 5, title: 'Lenda Farroupilha', bonusDesc: '+5% Poder Global Permanente', bonusStat: 'might', bonusValue: 0.05 },
    ],
  },
  {
    id: 'ghoul',
    name: 'Carniçal do Banzeiro',
    tier: 'swarm',
    spriteShape: 'ghoul',
    description: 'Cadáveres inchados do banhado que rastejam procurando o calor dos vivos.',
    lore: 'Corpos arrastados pelas cheias do rio Uruguai, amaldiçoados pela lama do banhado.',
    color: '#15803d',
    secondaryColor: '#14532d',
    baseHp: 45,
    baseDamage: 12,
    baseSpeed: 85,
    xpValue: 3,
    weakness: 'Fogo de Chão e Cachaça da Serra',
    milestones: [
      { kills: 25, rank: 1, title: 'Limpador de Banhado', bonusDesc: '+5% Pilas de Carniçais' },
      { kills: 100, rank: 2, title: 'Cinzas do Galpão', bonusDesc: '+10% Dano contra Carniçais' },
      { kills: 300, rank: 3, title: 'Imunizado', bonusDesc: '+20% XP de Carniçais' },
      { kills: 750, rank: 4, title: 'Guardião da Querência', bonusDesc: '+15 Vida Máxima Permanente', bonusStat: 'maxHp', bonusValue: 15 },
      { kills: 1500, rank: 5, title: 'Curandeiro Bagual', bonusDesc: '+0.3 HP/s Regeneração Permanente', bonusStat: 'hpRegen', bonusValue: 0.3 },
    ],
  },
  {
    id: 'wolf',
    name: 'Guaipeca Feroz da Campanha',
    tier: 'swarm',
    spriteShape: 'wolf',
    description: 'Caninos bravios de olhar chamejante que atacam em matilha veloz pelo descampado.',
    lore: 'Cães de guarda corrompidos que agora caçam qualquer vivente que cruze as taipas à noite.',
    color: '#44403c',
    secondaryColor: '#dc2626',
    baseHp: 55,
    baseDamage: 15,
    baseSpeed: 145,
    xpValue: 4,
    weakness: 'Boleadeiras e Versos do Martin Fierro',
    milestones: [
      { kills: 25, rank: 1, title: 'Domador de Guaipecas', bonusDesc: '+5% Pilas de Feras' },
      { kills: 100, rank: 2, title: 'Espanta-Feras', bonusDesc: '+10% Dano contra Guaipecas' },
      { kills: 300, rank: 3, title: 'Terror da Matilha', bonusDesc: '+20% XP de Guaipecas' },
      { kills: 750, rank: 4, title: 'Trote Selvagem', bonusDesc: '+10 Vel. Movimento Permanente', bonusStat: 'moveSpeed', bonusValue: 10 },
      { kills: 1500, rank: 5, title: 'Alfa dos Pampas', bonusDesc: '+5% Chance de Crítico Permanente', bonusStat: 'luck', bonusValue: 0.05 },
    ],
  },
  {
    id: 'wraith',
    name: 'Alma Penada do Cemitério',
    tier: 'elite',
    spriteShape: 'wraith',
    description: 'Espíritos errantes em mantos esfarrapados que flutuam emitindo lamentações campeiras.',
    lore: 'Almas de tropeiros que se perderam no minuano e vagam pelas cruzes do beira-estrada.',
    color: '#0891b2',
    secondaryColor: '#67e8f9',
    baseHp: 85,
    baseDamage: 18,
    baseSpeed: 95,
    xpValue: 6,
    weakness: 'Roda de Chimarrão e Faísca do Minuano',
    milestones: [
      { kills: 20, rank: 1, title: 'Benzedor Crioulo', bonusDesc: '+5% Pilas de Almas Penadas' },
      { kills: 80, rank: 2, title: 'Rompe-Assombrações', bonusDesc: '+10% Dano contra Almas' },
      { kills: 250, rank: 3, title: 'Paz aos Finados', bonusDesc: '+20% XP de Almas Penadas' },
      { kills: 600, rank: 4, title: 'Alma Serena', bonusDesc: '-3% Recarga Global Permanente', bonusStat: 'cooldownReduction', bonusValue: 0.03 },
      { kills: 1200, rank: 5, title: 'Respeitado no Além', bonusDesc: '+10% Área de Ataque Permanente', bonusStat: 'area', bonusValue: 0.1 },
    ],
  },
  {
    id: 'golem',
    name: 'Boitatá Petrificado',
    tier: 'elite',
    spriteShape: 'golem',
    description: 'Colosso de rocha de arenito e olhos de brasa viva, pesado como uma carreta carregada.',
    lore: 'Massa colossal de pedra missioneira guardiã dos tesouros jesuíticos enterrados.',
    color: '#52525b',
    secondaryColor: '#f97316',
    baseHp: 240,
    baseDamage: 24,
    baseSpeed: 55,
    xpValue: 12,
    weakness: 'Ponteiras de Aço e Fogo de Chão',
    milestones: [
      { kills: 15, rank: 1, title: 'Quebra-Pedreira', bonusDesc: '+8% Pilas de Colossos' },
      { kills: 50, rank: 2, title: 'Demolidor Missioneiro', bonusDesc: '+12% Dano contra Colossos' },
      { kills: 150, rank: 3, title: 'Racha-Pedra', bonusDesc: '+25% XP de Colossos' },
      { kills: 400, rank: 4, title: 'Couraça de Taurafé', bonusDesc: '+1 Armadura Permanente', bonusStat: 'armor', bonusValue: 1 },
      { kills: 800, rank: 5, title: 'Coração de Brasa', bonusDesc: '+8% Poder Global Permanente', bonusStat: 'might', bonusValue: 0.08 },
    ],
  },
  {
    id: 'boss_king',
    name: 'Coronel das Trevas (O Tirano)',
    tier: 'boss',
    spriteShape: 'boss_king',
    description: 'O tirano do terceiro minuto. Antigo caudilho cruel que comanda hordas a ferro e fogo.',
    lore: 'Um estancieiro ganancioso que vendeu a própria alma na encruzilhada por poder eterno.',
    color: '#f59e0b',
    secondaryColor: '#991b1b',
    baseHp: 1500,
    baseDamage: 25,
    baseSpeed: 75,
    xpValue: 50,
    weakness: 'Dano concentrado veloz e acertos críticos de relho',
    milestones: [
      { kills: 3, rank: 1, title: 'Derruba-Caudilho', bonusDesc: 'Baús do Coronel dão +10% Pilas' },
      { kills: 10, rank: 2, title: 'Destronador de Tiranos', bonusDesc: '+15% Dano contra o Coronel' },
      { kills: 25, rank: 3, title: 'Herói dos Pampas', bonusDesc: '+35% XP do Coronel' },
      { kills: 60, rank: 4, title: 'Braço Farroupilha', bonusDesc: '+1 Projétil Extra Global Permanente', bonusStat: 'amount', bonusValue: 1 },
      { kills: 150, rank: 5, title: 'Lenda Baguala', bonusDesc: '+10% Poder & +5% Sorte Global', bonusStat: 'might', bonusValue: 0.1 },
    ],
  },
  {
    id: 'vampire_lord',
    name: 'Barão da Fronteira Maldita',
    tier: 'boss',
    spriteShape: 'vampire_lord',
    description: 'O mestre da noite sangrenta no quinto minuto. Vampiro nobre que assola as estâncias.',
    lore: 'Vindo de além-mar no século retrasado, instalou-se na fronteira drenando a vida dos campeiros.',
    color: '#7f1d1d',
    secondaryColor: '#dc2626',
    baseHp: 3500,
    baseDamage: 35,
    baseSpeed: 90,
    xpValue: 100,
    weakness: 'Fusões Supremas (Relho Farroupilha / Fogo de Chão)',
    milestones: [
      { kills: 2, rank: 1, title: 'Caçador de Barões', bonusDesc: 'Baús do Barão dão +20% Pilas' },
      { kills: 8, rank: 2, title: 'Flagelo Noturno', bonusDesc: '+15% Dano contra o Barão' },
      { kills: 20, rank: 3, title: 'Exorcista Campeiro', bonusDesc: '+40% XP do Barão' },
      { kills: 50, rank: 4, title: 'Sangue Gauchesco', bonusDesc: '+1 Reza Forte Extra Permanente', bonusStat: 'revives', bonusValue: 1 },
      { kills: 100, rank: 5, title: 'Sol da Querência', bonusDesc: '+15% Poder Global Permanente', bonusStat: 'might', bonusValue: 0.15 },
    ],
  },
  {
    id: 'reaper',
    name: 'A Morte Baguala (O Ceifador da Querência)',
    tier: 'boss',
    spriteShape: 'reaper',
    description: 'A ceifadora do décimo minuto. Empunha foice afiada e cavalga o minuano da morte.',
    lore: 'A lenda diz que quando o minuano gela a espinha e o relógio marca o fim, a Morte vem buscar quem sobrou.',
    color: '#09090b',
    secondaryColor: '#ef4444',
    baseHp: 99999,
    baseDamage: 999,
    baseSpeed: 120,
    xpValue: 500,
    weakness: 'Fusões Supremas no auge e Geada Negra',
    milestones: [
      { kills: 1, rank: 1, title: 'Peleador da Morte', bonusDesc: '+500 Pilas Imediatas' },
      { kills: 3, rank: 2, title: 'Gaudério Imortal', bonusDesc: '+20% Dano contra a Morte' },
      { kills: 10, rank: 3, title: 'Além da Querência', bonusDesc: '+50% XP da Morte Baguala' },
      { kills: 25, rank: 4, title: 'Mito Campeiro', bonusDesc: '+20% Dano Global Permanente', bonusStat: 'might', bonusValue: 0.2 },
      { kills: 50, rank: 5, title: 'Rei do Pampa Eterno', bonusDesc: '+25% Poder & +2 Rezas Fortes', bonusStat: 'might', bonusValue: 0.25 },
    ],
  },
  {
    id: 'gaucho_apartamento',
    name: 'Gaúcho de Apartamento',
    tier: 'swarm',
    spriteShape: 'gaucho_apartamento',
    description: 'Bermuda xadrez, cuia elétrica, copo térmico e churrasco feito em grelha de condomínio.',
    lore: 'Diz que é farroupilha raiz, mas se chover ou faltar Wi-Fi ele entra em pânico. Arremessa copos térmicos e brownies.',
    color: '#0284c7',
    secondaryColor: '#f43f5e',
    baseHp: 52,
    baseDamage: 12,
    baseSpeed: 135,
    xpValue: 4,
    weakness: 'Churrasco de Chão e Fumo de Rolo',
    milestones: [
      { kills: 30, rank: 1, title: 'Fiscal de Churrasqueira', bonusDesc: '+5% Pilas de Condomínio' },
      { kills: 100, rank: 2, title: 'Sem Wi-Fi', bonusDesc: '+10% Dano contra Gaúchos de Apartamento' },
      { kills: 350, rank: 3, title: 'Grelha Raiz', bonusDesc: '+20% XP de Gaúchos de Apartamento' },
      { kills: 800, rank: 4, title: 'Alma Farrapa', bonusDesc: '+12 Vida Máxima Permanente', bonusStat: 'maxHp', bonusValue: 12 },
      { kills: 1600, rank: 5, title: 'Gaudério Genuíno', bonusDesc: '+5% Movimento Global', bonusStat: 'moveSpeed', bonusValue: 5 },
    ],
  },
  {
    id: 'saci',
    name: 'Saci-Pererê dos Capões',
    tier: 'swarm',
    spriteShape: 'saci',
    description: 'Pula veloz em uma perna só dentro de redemoinhos de poeira e espalha travessuras na escuridão.',
    lore: 'Espírito lendário travesso dos capões que azeda o mate, trança as crinas dos potros e assobia no vento minuano.',
    color: '#b91c1c',
    secondaryColor: '#f59e0b',
    baseHp: 65,
    baseDamage: 14,
    baseSpeed: 165,
    xpValue: 5,
    weakness: 'Peneira de Taquara e Faíscas Elétricas',
    milestones: [
      { kills: 25, rank: 1, title: 'Apanhador de Redemoinho', bonusDesc: '+5% Pilas de Sacis' },
      { kills: 90, rank: 2, title: 'Sem Carapuça', bonusDesc: '+12% Dano contra Sacis' },
      { kills: 300, rank: 3, title: 'Amansador de Folclore', bonusDesc: '+25% XP de Sacis' },
      { kills: 700, rank: 4, title: 'Pulo do Campeiro', bonusDesc: '+10 Velocidade Permanente', bonusStat: 'moveSpeed', bonusValue: 10 },
      { kills: 1500, rank: 5, title: 'Mestre dos Capões', bonusDesc: '+5% Sorte Global Permanente', bonusStat: 'luck', bonusValue: 0.05 },
    ],
  },
  {
    id: 'curupira',
    name: 'Curupira dos Pinheirais',
    tier: 'elite',
    spriteShape: 'curupira',
    description: 'Guardião selvagem das araucárias com pés virados para trás e cabelos flamejantes que confundem os caçadores.',
    lore: 'Defensor feroz da fauna e flora gaúcha. Quem quebra galho de pinheiro ou maltrata cusco sofre sua ira na mata.',
    color: '#ea580c',
    secondaryColor: '#15803d',
    baseHp: 340,
    baseDamage: 25,
    baseSpeed: 115,
    xpValue: 18,
    weakness: 'Boleadeiras e Espeto Flamejante',
    milestones: [
      { kills: 15, rank: 1, title: 'Rastreador Invertido', bonusDesc: '+8% Pilas de Curupiras' },
      { kills: 60, rank: 2, title: 'Amigo das Araucárias', bonusDesc: '+15% Dano contra Curupiras' },
      { kills: 180, rank: 3, title: 'Guardião da Mata', bonusDesc: '+30% XP de Curupiras' },
      { kills: 450, rank: 4, title: 'Raízes Fortes', bonusDesc: '+1 Armadura Permanente', bonusStat: 'armor', bonusValue: 1 },
      { kills: 900, rank: 5, title: 'Voz da Natureza', bonusDesc: '+8% Poder Permanente', bonusStat: 'might', bonusValue: 0.08 },
    ],
  },
  {
    id: 'mula_sem_cabeca',
    name: 'Mula Sem Cabeça do Arrabalde',
    tier: 'elite',
    spriteShape: 'mula_sem_cabeca',
    description: 'Criatura terrível galopando a toda velocidade com labaredas de fogo vivo saindo do pescoço e relincho de trovão.',
    lore: 'Nas noites sem lua, o relincho flamejante ecoa pelas encruzilhadas assustando as estâncias até o raiar do sol.',
    color: '#7f1d1d',
    secondaryColor: '#f97316',
    baseHp: 480,
    baseDamage: 32,
    baseSpeed: 175,
    xpValue: 24,
    weakness: 'Água Sagrada e Gaitaço Ininterrupto',
    milestones: [
      { kills: 12, rank: 1, title: 'Domador do Fogo', bonusDesc: '+10% Pilas da Mula' },
      { kills: 45, rank: 2, title: 'Ferradura Quebrada', bonusDesc: '+15% Dano contra a Mula' },
      { kills: 140, rank: 3, title: 'Exorcista Noturno', bonusDesc: '+30% XP da Mula' },
      { kills: 350, rank: 4, title: 'Galope Implacável', bonusDesc: '+12 Vel. Movimento Permanente', bonusStat: 'moveSpeed', bonusValue: 12 },
      { kills: 750, rank: 5, title: 'Chama Domada', bonusDesc: '+10% Dano Global Permanente', bonusStat: 'might', bonusValue: 0.1 },
    ],
  },
  {
    id: 'boss_boitata',
    name: 'Boitatá Ancestral (A Serpente Flamejante)',
    tier: 'boss',
    spriteShape: 'boss_boitata',
    description: 'Chefe do minuto 7: Serpente colossal de fogo e olhos fulgurantes que queima o solo por onde rasteja.',
    lore: 'Antiga serpente que devorou os olhos dos animais durante a grande noite das trevas, emanando labaredas vivas.',
    color: '#f97316',
    secondaryColor: '#ef4444',
    baseHp: 5800,
    baseDamage: 38,
    baseSpeed: 95,
    xpValue: 180,
    weakness: 'Matilha de Cuscos e Rajadas de Trabuco Farrapo',
    milestones: [
      { kills: 2, rank: 1, title: 'Olhos de Fogo', bonusDesc: 'Baús do Boitatá dão +20% Pilas' },
      { kills: 6, rank: 2, title: 'Domador de Serpentes', bonusDesc: '+20% Dano contra o Boitatá' },
      { kills: 18, rank: 3, title: 'Fogo Sob Controle', bonusDesc: '+40% XP do Boitatá' },
      { kills: 40, rank: 4, title: 'Brasas Sagradas', bonusDesc: '+10% Área Global Permanente', bonusStat: 'area', bonusValue: 0.1 },
      { kills: 90, rank: 5, title: 'Senhor do Fogo de Chão', bonusDesc: '+15% Dano Global Permanente', bonusStat: 'might', bonusValue: 0.15 },
    ],
  },
  {
    id: 'boss_teiniagua',
    name: 'A Teiniaguá Encantada do Jarau',
    tier: 'boss',
    spriteShape: 'boss_teiniagua',
    description: 'Chefe do minuto 9: Lagartixa mística gigante com cabeça de princesa e carbúnculo de rubi na fronte.',
    lore: 'Princesa encantada das profundezas do Cerro do Jarau, guardiã dos maiores mistérios do folclore gaúcho.',
    color: '#047857',
    secondaryColor: '#f43f5e',
    baseHp: 8500,
    baseDamage: 44,
    baseSpeed: 105,
    xpValue: 260,
    weakness: 'Fusões Supremas e Companheiros Cuscos',
    milestones: [
      { kills: 1, rank: 1, title: 'Segredo do Jarau', bonusDesc: 'Baús da Teiniaguá dão +25% Pilas' },
      { kills: 5, rank: 2, title: 'Encantamento Quebrado', bonusDesc: '+20% Dano contra a Teiniaguá' },
      { kills: 15, rank: 3, title: 'Lenda Missioneira', bonusDesc: '+50% XP da Teiniaguá' },
      { kills: 35, rank: 4, title: 'Rubi do Jarau', bonusDesc: '+10% Sorte e Crítico Permanente', bonusStat: 'luck', bonusValue: 0.1 },
      { kills: 75, rank: 5, title: 'Soberano das Lendas', bonusDesc: '+20% Dano Global & +1 Reza Forte', bonusStat: 'might', bonusValue: 0.2 },
    ],
  },
  {
    id: 'boss_negrinho',
    name: 'O Negrinho do Pastoreio (Espírito das Velas Bentas)',
    tier: 'boss',
    spriteShape: 'boss_negrinho',
    description: 'Chefe lendário dos 15 minutos: Menino milagroso montado em seu veloz cavalo baio, rodeado por velas bentas e luz celestial.',
    lore: 'A lenda mais venerada do Rio Grande do Sul. Protegido pela Virgem Maria após o martírio nas mãos de um estancieiro perverso, cavalga eternamente pelo pampa com sua vela que nunca apaga, achando tudo que foi perdido e concedendo milagres aos aflitos.',
    color: '#facc15',
    secondaryColor: '#3b82f6',
    baseHp: 18000,
    baseDamage: 45,
    baseSpeed: 100,
    xpValue: 400,
    weakness: 'Respeito à lenda, esquiva veloz dos círculos de velas e fusões no auge',
    milestones: [
      { kills: 1, rank: 1, title: 'Acendedor de Velas', bonusDesc: 'Baús do Negrinho dão +30% Pilas' },
      { kills: 3, rank: 2, title: 'Devoto do Pastoreio', bonusDesc: '+20% Dano contra o Negrinho' },
      { kills: 8, rank: 3, title: 'Amigo do Cavalo Baio', bonusDesc: '+50% XP do Negrinho' },
      { kills: 20, rank: 4, title: 'Milagre Alcançado', bonusDesc: '+20% Sorte Permanente', bonusStat: 'luck', bonusValue: 0.2 },
      { kills: 50, rank: 5, title: 'Protetor das Missões', bonusDesc: '+25% Poder & +1 Reza Forte Extra Permanente', bonusStat: 'might', bonusValue: 0.25 },
    ],
  },
];

// Returns the active percentage damage bonus against a specific monster species based on kills
// e.g., 100 kills = +5%, 500 kills = +10%, 1500 kills = +15%, 3000+ kills = +25%
export function getMonsterSpeciesDamageMultiplier(speciesId: string, kills: number): number {
  let bonus = 0;
  if (kills >= 100) bonus += 0.05;
  if (kills >= 500) bonus += 0.05;
  if (kills >= 1500) bonus += 0.05;
  if (kills >= 3000) bonus += 0.10;
  return bonus;
}

// Next milestone threshold for killer rewards
export function getNextKillMilestone(kills: number): { nextGoal: number; bonusText: string } | null {
  if (kills < 100) return { nextGoal: 100, bonusText: '+5% de Dano contra a espécie' };
  if (kills < 500) return { nextGoal: 500, bonusText: '+10% de Dano contra a espécie' };
  if (kills < 1500) return { nextGoal: 1500, bonusText: '+15% de Dano (+5% extra) contra a espécie' };
  if (kills < 3000) return { nextGoal: 3000, bonusText: '+25% de Dano Máximo contra a espécie' };
  return null;
}


